version: 5.1.0
variant: default
logo: 
    light: https://p0.meituan.net/csc/9d92e3239ccf0a799a2f00418564f4b2108562.png
    dark: https://p0.meituan.net/csc/9d92e3239ccf0a799a2f00418564f4b2108562.png
head:
    favicon: https://p0.meituan.net/csc/9d92e3239ccf0a799a2f00418564f4b2108562.png
    #manifest:
    #    name: 
    #    short_name: 
    #    start_url: 
    #    theme_color: 
    #    background_color: 
    #    display: standalone
    #    icons:
    #        -
    #            src: ''
    #            sizes: ''
    #            type: 
    #open_graph:
    #    title: 
    #    type: blog
    #    url: 
    #    image: 
    #    site_name: 
    #    author: 
    #    description: 
    #    twitter_card: 
    #    twitter_id: 
    #    twitter_site: 
    #    google_plus: 
    #    fb_admins: 
    #    fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: /atom.xml
navbar:
    menu:
        首页: /
        时间轴: /archives/
        分类: /categories/
        标签: /tags/
        友情链接: /friends/
        关于: /about/
    links: 
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/deed.zh
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/deed.zh
search:
    type: insight
comment:
    type: twikoo
    env_id: https://twikoo.tcea.top
    jsUrl: https://cdn.jsdelivr.net/npm/twikoo@1.6.17/dist/twikoo.all.min.js
    region: ap-guangzhou     # Optional
    lang: zh-CN              # Optional

    #type: valine
    #app_id: dIoIKwhCkzyyIwYfEIKuCbn3-gzGzoHsz
    #app_key: gJ4jOsrznFSTT6CklNNd9TWE
donates:
    -
        type: alipay
        qrcode: https://p0.meituan.net/csc/ab5b85a443cd601158ebddf7613b4f77197446.jpg
    -
        type: wechat
        qrcode: https://p0.meituan.net/csc/140e679555dfdbd5111567859ecdb31f105210.png
share:
    type: sharejs
sidebar:
    left:
        sticky: true
    right:
        sticky: true
widgets:
    -
        position: left
        type: profile
        author: 白鼠
        author_title: 白鼠的小站
        location: 中国，山东
        avatar: https://p0.meituan.net/csc/9d92e3239ccf0a799a2f00418564f4b2108562.png
        avatar_rounded: true
        gravatar: 
        social_links:
            QQ:
                icon: fab fa-qq
                url: 'tencent://message/?uin=1506400017&Site=www.tcea.top&Menu=yes'
            Mail:
                icon: fas fa-envelope
                url: 'mailto:official@tcea.com'
            RSS:
                icon: fas fa-rss
                url: '/atom.xml'
 # Archives widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: archives
    # Categories widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: categories
    # Tags widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: tags
    # Recommendation links widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: links
        # Names and URLs of the sites
        links:
            Cyanogen Community: 'https://qcea.top'
    # Google AdSense unit configurations
    #-
    #    # Where should the widget be placed, left sidebar or right sidebar
    #    position: left
    #    type: adsense
    #    # AdSense client ID
    #    client_id: 'ca-pub-5716633754544549'
    #    # AdSense AD unit ID
    #    slot_id: '6035187824'
    # Table of contents widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: toc
    # Recent posts widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: recent_posts
    # Google FeedBurner email subscription widget configurations
    #-
    #    Where should the widget be placed, left sidebar or right sidebar
    #    position: right
    #    type: subscribe_email
        # Hint text under the email input
    #    description: Powered by Google feedburner
        # Feedburner ID
    #    feedburner_id: 'imaegoo'
plugins:
    animejs: true
    back_to_top: true
    #baidu_analytics:
    #    tracking_id: 
    #bing_webmaster:
    #    tracking_id: 
    busuanzi: false
    gallery: true
    katex: false
    mathjax: false
    outdated_browser: true
    progressbar: true
providers:
    cdn: loli
    fontcdn: loli
    iconcdn: loli
